### ISSUE TITLE
everything is down

### ISSUE THREAD

**Issue by jaygearhead** [raphcadiz/gravity2pdf#1]
What is going on? Do we need to find another solution? gravity2pdf is offline, merges do not work on our site and we are stuck. please advise- Jason

**Comment by raphcadiz** [comment]
Currently the server is down, we're trying to fix it at the moment. We will keep you posted

**Comment by jaygearhead** [comment]
Any work around? Why does this break merges on our site?

**Comment by kazpsp** [comment]
same here, why would your server affect ours?

**Comment by raphcadiz** [comment]
It's backup now!
The reason is the plugin is connecting to our API in order to generate or map to PDF data. We realize not all server has PDFTK on it or you will be hassle to install it to your server. So we make an API to do it for you instead.

**Comment by jaygearhead** [comment]
PDFTK is available for not much $, how do we setup an API to host? Hostgator does not allow it to be installed, but we have other options that can. Can you please provide instructions or where to find? Thanks, Jason

looking forward to v3!
